name: Build LaTeX document

on:
  push:
    branches:    
      - 'devm'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Build LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: template.tex

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: PedroBailao
          author_email: p.bailao@campus.fct.unl.pt
          message: 'Auto-updating PDF File'
          add: 'template.pdf'